### ISSUE TITLE
--worldlist argument can't start from ~

### ISSUE THREAD

**Issue by bl4de** [jobertabma/virtual-host-discovery#5]
Hi @jobertabma,

This is very, very, very small issue I've found and it does not stop from using your tool in any way, however I just want to notify you about this. Just in case ;)

So, when I run scan.rb with following options:

```
ruby scan.rb --ip=XX.XX.XX.XX --host=xxx.com  --ignore-http-codes=301,400,403 --wordlist=~/hacking/dictionaries/SecLists/Discovery/DNS/subdomains-top1mil-5000.txt

```

I've got following error:

```
scan.rb:57:in `read': No such file or directory @ rb_sysopen - ~/hacking/dictionaries/SecLists/Discovery/DNS/subdomains-top1mil-5000.txt (Errno::ENOENT)
	from scan.rb:57:in `<main>'
```

Changing ```~``` into full directory path resolves problem:

```
ruby scan.rb --ip=XX.XX.XX.XX --host=xxx.com  --ignore-http-codes=301,400,403 --wordlist=/Users/bl4de/hacking/dictionaries/SecLists/Discovery/DNS/subdomains-top1mil-5000.txt

```

Let me know if you need any further information about this issue.

Thank you!

Regards,

Rafal 'bl4de' Janicki
hackerone.com/bl4de
twitter.com/_bl4de

**Comment by jobertabma** [comment]
Thanks for flagging, @bl4de, this is now fixed!
